### ISSUE TITLE
dotfiles.sh wants to link .git

### ISSUE THREAD

**Issue by rhofour** [wking/dotfiles-framework#1]
Unless I'm missing something this seems like unwanted behaviour. I see no reason why the git information that's attaches to my dotfiles should actually end up in my home directory with them.

**Comment by wking** [comment]
I'm not entirely clear on what your problem is.  Did you already have
a ~/.git before using dotfiles.sh?  What does it track?

I just pushed v0.4 which adds a 'list' command so you can see the
dotfiles repositories you're using.  Maybe it would help to see what
that shows on your system.  If you're comfortable posting a (possibly
redacted) form here, that might help too.

**Comment by rhofour** [comment]
Never mind that. The problem was with my repo (I'd accidentally moved .git into src/).
